"""new tables

Revision ID: fbff9df38f4a
Revises: 
Create Date: 2026-04-28 22:25:52.906997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbff9df38f4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.Enum('FOUNDATION', 'SCORING', 'CALIBRATION', 'OUTCOME', 'GENERATIVE', name='model_kind'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_uri', sa.Text(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    op.create_index('ix_model_registry_kind_active', 'model_registry', ['kind', 'is_active'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('billing_email', sa.String(length=320), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='api_key_status'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('key_prefix')
    )
    op.create_index('ix_api_keys_org_status', 'api_keys', ['organization_id', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_created_at', 'audit_logs', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_org_created_at', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='org_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_user_membership')
    )
    op.create_table('organization_sso_configs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('provider_type', sa.Enum('oidc', 'saml', name='sso_provider_type'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('issuer_url', sa.Text(), nullable=True),
    sa.Column('entrypoint_url', sa.Text(), nullable=True),
    sa.Column('metadata_url', sa.Text(), nullable=True),
    sa.Column('audience', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('scopes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attribute_mapping_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=True),
    sa.Column('login_hint_domain', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_organization_sso_config_org')
    )
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.String(length=255), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_org_created_at', 'projects', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_projects_org_name', 'projects', ['organization_id', 'name'], unique=False)
    op.create_table('settings',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('env_name', sa.String(length=120), nullable=False),
    sa.Column('group_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_settings_org_key')
    )
    op.create_index('ix_settings_org_group', 'settings', ['organization_id', 'group_id'], unique=False)
    op.create_table('user_mfa_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('method_type', sa.Enum('totp', name='mfa_method_type'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('pending_secret_ciphertext', sa.Text(), nullable=True),
    sa.Column('recovery_code_hashes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'method_type', name='uq_user_mfa_credential_method')
    )
    op.create_index('ix_user_mfa_credentials_user_enabled', 'user_mfa_credentials', ['user_id', 'is_enabled'], unique=False)
    op.create_table('user_sessions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_family_id', sa.UUID(), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=120), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('replaced_by_session_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_user_sessions_token_hash')
    )
    op.create_index('ix_user_sessions_org_user', 'user_sessions', ['organization_id', 'user_id'], unique=False)
    op.create_index('ix_user_sessions_user_revoked', 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('subscribed_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_endpoints_org_active', 'webhook_endpoints', ['organization_id', 'is_active'], unique=False)
    op.create_table('workspace_invites',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=False),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='org_role'), nullable=False),
    sa.Column('token_prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', 'expired', name='workspace_invite_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_workspace_invites_token_hash')
    )
    op.create_index('ix_workspace_invites_email_status', 'workspace_invites', ['email', 'status'], unique=False)
    op.create_index('ix_workspace_invites_org_status', 'workspace_invites', ['organization_id', 'status'], unique=False)
    op.create_table('campaigns',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('audience_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_campaigns_project_name', 'campaigns', ['project_id', 'name'], unique=False)
    op.create_table('collaboration_reviews',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('analysis_job', 'analysis_comparison', name='collaboration_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'changes_requested', 'approved', name='review_status'), nullable=False),
    sa.Column('review_summary', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'entity_type', 'entity_id', name='uq_collaboration_review_entity')
    )
    op.create_index('ix_collaboration_reviews_project_assignee', 'collaboration_reviews', ['project_id', 'assignee_user_id'], unique=False)
    op.create_index('ix_collaboration_reviews_project_status', 'collaboration_reviews', ['project_id', 'status'], unique=False)
    op.create_table('creative_comparisons',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('comparison_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creative_comparisons_project_name', 'creative_comparisons', ['project_id', 'name'], unique=False)
    op.create_table('creatives',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'TEXT', 'HTML', 'URL', name='asset_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'ARCHIVED', name='creative_status'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creatives_project_name', 'creatives', ['project_id', 'name'], unique=False)
    op.create_index('ix_creatives_project_status', 'creatives', ['project_id', 'status'], unique=False)
    op.create_table('collaboration_comments',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=True),
    sa.Column('segment_label', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['collaboration_reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collaboration_comments_review_created_at', 'collaboration_comments', ['review_id', 'created_at'], unique=False)
    op.create_table('creative_versions',
    sa.Column('creative_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('html_snapshot_uri', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('frame_rate', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('extracted_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preprocessing_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_id', 'version_number', name='uq_creative_version_number')
    )
    op.create_index('ix_creative_versions_creative_latest', 'creative_versions', ['creative_id', 'is_current'], unique=False)
    op.create_table('asset_embeddings',
    sa.Column('creative_version_id', sa.UUID(), nullable=False),
    sa.Column('embedding_kind', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('vector_dim', sa.Integer(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('vector_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('creative_version_id', 'embedding_kind', 'model_name', name='uq_asset_embedding_version_kind_model')
    )
    op.create_index('ix_asset_embeddings_version_kind', 'asset_embeddings', ['creative_version_id', 'embedding_kind'], unique=False)
    op.create_table('creative_comparison_items',
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=False),
    sa.Column('creative_version_id', sa.UUID(), nullable=False),
    sa.Column('candidate_rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['creative_comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_id', 'creative_version_id', name='uq_comparison_version')
    )
    op.create_index('ix_creative_comparison_items_rank', 'creative_comparison_items', ['comparison_id', 'candidate_rank'], unique=False)
    op.create_table('creative_comparison_results',
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('winning_creative_version_id', sa.UUID(), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['creative_comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_creative_version_id'], ['creative_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_id', name='uq_comparison_result_comparison')
    )
    op.create_table('inference_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=False),
    sa.Column('creative_version_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('prediction_type', sa.Enum('SINGLE_ASSET', 'COMPARISON', 'OPTIMIZATION', 'BATCH', name='prediction_type'), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PREPROCESSING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='job_status'), nullable=False),
    sa.Column('tribe_model_id', sa.UUID(), nullable=True),
    sa.Column('scoring_model_id', sa.UUID(), nullable=True),
    sa.Column('calibration_model_id', sa.UUID(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runtime_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_surface', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=40), nullable=True),
    sa.Column('goal_template', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=True),
    sa.Column('audience_segment', sa.String(length=255), nullable=True),
    sa.Column('execution_phase', sa.String(length=40), nullable=True),
    sa.Column('execution_phase_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['calibration_model_id'], ['model_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoring_model_id'], ['model_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tribe_model_id'], ['model_registry.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inference_jobs_created_at', 'inference_jobs', ['created_at'], unique=False)
    op.create_index('ix_inference_jobs_creative_status', 'inference_jobs', ['creative_id', 'status'], unique=False)
    op.create_index('ix_inference_jobs_execution_phase', 'inference_jobs', ['execution_phase'], unique=False)
    op.create_index('ix_inference_jobs_execution_phase_updated_at', 'inference_jobs', ['execution_phase', 'execution_phase_updated_at'], unique=False)
    op.create_index('ix_inference_jobs_project_channel', 'inference_jobs', ['project_id', 'channel'], unique=False)
    op.create_index('ix_inference_jobs_project_goal_template', 'inference_jobs', ['project_id', 'goal_template'], unique=False)
    op.create_index('ix_inference_jobs_project_status', 'inference_jobs', ['project_id', 'status'], unique=False)
    op.create_index('ix_inference_jobs_project_status_surface_media_created_desc', 'inference_jobs', ['project_id', 'status', 'analysis_surface', 'media_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_inference_jobs_project_user_created_at', 'inference_jobs', ['project_id', 'created_by_user_id', 'created_at'], unique=False)
    op.create_index('ix_inference_jobs_project_user_surface_media_created', 'inference_jobs', ['project_id', 'created_by_user_id', 'analysis_surface', 'media_type', 'created_at'], unique=False)
    op.create_index('ix_inference_jobs_project_user_surface_media_created_desc', 'inference_jobs', ['project_id', 'created_by_user_id', 'analysis_surface', 'media_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_inference_jobs_status_created_at_desc', 'inference_jobs', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('outcome_events',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=True),
    sa.Column('creative_version_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('metric_type', sa.Enum('CTR', 'CVR', 'CPC', 'CPA', 'ROAS', 'WATCH_TIME', 'THUMB_STOP_RATE', 'COMPLETION_RATE', 'BOUNCE_RATE', 'SCROLL_DEPTH', name='outcome_metric_type'), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('metric_unit', sa.String(length=40), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_system', sa.String(length=120), nullable=True),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outcome_events_creative_metric', 'outcome_events', ['creative_id', 'metric_type'], unique=False)
    op.create_index('ix_outcome_events_observed_at', 'outcome_events', ['observed_at'], unique=False)
    op.create_index('ix_outcome_events_project_metric', 'outcome_events', ['project_id', 'metric_type'], unique=False)
    op.create_table('stored_artifacts',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('creative_id', sa.UUID(), nullable=True),
    sa.Column('creative_version_id', sa.UUID(), nullable=True),
    sa.Column('artifact_kind', sa.String(length=50), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('media_type', sa.String(length=40), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('upload_status', sa.Enum('PENDING', 'UPLOADING', 'STORED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_name', 'storage_key', name='uq_artifact_bucket_key')
    )
    op.create_index('ix_stored_artifacts_project_kind', 'stored_artifacts', ['project_id', 'artifact_kind'], unique=False)
    op.create_index('ix_stored_artifacts_project_user_kind_status_created_desc', 'stored_artifacts', ['project_id', 'created_by_user_id', 'artifact_kind', 'upload_status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_stored_artifacts_project_user_kind_status_media_created_desc', 'stored_artifacts', ['project_id', 'created_by_user_id', 'artifact_kind', 'upload_status', 'media_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_stored_artifacts_storage_key', 'stored_artifacts', ['storage_key'], unique=False)
    op.create_index('ix_stored_artifacts_user_status', 'stored_artifacts', ['created_by_user_id', 'upload_status'], unique=False)
    op.create_table('analysis_results',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('segments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visualizations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_analysis_result_job')
    )
    op.create_index('ix_analysis_results_job_created_at', 'analysis_results', ['job_id', 'created_at'], unique=False)
    op.create_table('creative_comparison_item_results',
    sa.Column('comparison_result_id', sa.UUID(), nullable=False),
    sa.Column('creative_version_id', sa.UUID(), nullable=False),
    sa.Column('overall_rank', sa.Integer(), nullable=False),
    sa.Column('scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_result_id'], ['creative_comparison_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_result_id', 'creative_version_id', name='uq_comparison_item_result_version')
    )
    op.create_table('job_metrics',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('metric_unit', sa.String(length=40), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_metrics_job_name', 'job_metrics', ['job_id', 'metric_name'], unique=False)
    op.create_table('llm_evaluations',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('model_provider', sa.String(length=120), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('prompt_version', sa.String(length=80), nullable=True),
    sa.Column('input_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'mode', name='uq_llm_evaluations_job_mode')
    )
    op.create_index('ix_llm_evaluations_job_status', 'llm_evaluations', ['job_id', 'status'], unique=False)
    op.create_index('ix_llm_evaluations_user_created_at', 'llm_evaluations', ['user_id', 'created_at'], unique=False)
    op.create_table('prediction_results',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('creative_id', sa.UUID(), nullable=False),
    sa.Column('creative_version_id', sa.UUID(), nullable=False),
    sa.Column('raw_brain_response_uri', sa.Text(), nullable=True),
    sa.Column('raw_brain_response_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reduced_feature_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('region_activation_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['inference_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_prediction_result_job')
    )
    op.create_index('ix_prediction_results_project_created_at', 'prediction_results', ['project_id', 'created_at'], unique=False)
    op.create_index('ix_prediction_results_version_created_at', 'prediction_results', ['creative_version_id', 'created_at'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('creative_id', sa.UUID(), nullable=True),
    sa.Column('creative_version_id', sa.UUID(), nullable=True),
    sa.Column('upload_token', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'STORED', 'FAILED', name='upload_status'), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('expected_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_artifact_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creative_version_id'], ['creative_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_artifact_id'], ['stored_artifacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_token', name='uq_upload_sessions_token')
    )
    op.create_index('ix_upload_sessions_project_status', 'upload_sessions', ['project_id', 'status'], unique=False)
    op.create_index('ix_upload_sessions_user_status', 'upload_sessions', ['created_by_user_id', 'status'], unique=False)
    op.create_index('ix_upload_sessions_user_status_created_desc', 'upload_sessions', ['created_by_user_id', 'status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('calibration_observations',
    sa.Column('prediction_result_id', sa.UUID(), nullable=False),
    sa.Column('outcome_event_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.Enum('ATTENTION', 'EMOTION', 'MEMORY', 'COGNITIVE_LOAD', 'CONVERSION_PROXY', 'BRAND_CLARITY', 'CTA_CLARITY', 'NOVELTY', 'FATIGUE_RISK', name='calibration_score_type'), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('metric_type', sa.Enum('CTR', 'CVR', 'CPC', 'CPA', 'ROAS', 'WATCH_TIME', 'THUMB_STOP_RATE', 'COMPLETION_RATE', 'BOUNCE_RATE', 'SCROLL_DEPTH', name='calibration_metric_type'), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_event_id'], ['outcome_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_result_id'], ['prediction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calibration_observations_metric_type', 'calibration_observations', ['metric_type'], unique=False)
    op.create_index('ix_calibration_observations_score_type', 'calibration_observations', ['score_type'], unique=False)
    op.create_table('optimization_suggestions',
    sa.Column('prediction_result_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_type', sa.Enum('COPY', 'LAYOUT', 'COLOR', 'CTA', 'FRAMING', 'PACING', 'THUMBNAIL', 'BRANDING', name='suggestion_type'), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'ACCEPTED', 'REJECTED', 'APPLIED', name='suggestion_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('proposed_change_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_score_lift_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_result_id'], ['prediction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_optimization_suggestions_result_status', 'optimization_suggestions', ['prediction_result_id', 'status'], unique=False)
    op.create_table('prediction_scores',
    sa.Column('prediction_result_id', sa.UUID(), nullable=False),
    sa.Column('score_type', sa.Enum('ATTENTION', 'EMOTION', 'MEMORY', 'COGNITIVE_LOAD', 'CONVERSION_PROXY', 'BRAND_CLARITY', 'CTA_CLARITY', 'NOVELTY', 'FATIGUE_RISK', name='score_type'), nullable=False),
    sa.Column('normalized_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('percentile', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_result_id'], ['prediction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_result_id', 'score_type', name='uq_prediction_score_type')
    )
    op.create_index('ix_prediction_scores_type_value', 'prediction_scores', ['score_type', 'normalized_score'], unique=False)
    op.create_table('prediction_timeline_points',
    sa.Column('prediction_result_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('attention_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('emotion_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('memory_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cognitive_load_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('conversion_proxy_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_result_id'], ['prediction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_timeline_points_result_time', 'prediction_timeline_points', ['prediction_result_id', 'timestamp_ms'], unique=False)
    op.create_table('prediction_visualizations',
    sa.Column('prediction_result_id', sa.UUID(), nullable=False),
    sa.Column('visualization_type', sa.Enum('HEATMAP', 'TIMELINE', 'SALIENCY', 'FRAME_GRID', 'BRAIN_REGION_SUMMARY', name='visualization_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('storage_uri', sa.Text(), nullable=True),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_result_id'], ['prediction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prediction_visualizations_type', 'prediction_visualizations', ['prediction_result_id', 'visualization_type'], unique=False)
    op.create_table('generated_variants',
    sa.Column('parent_creative_version_id', sa.UUID(), nullable=False),
    sa.Column('optimization_suggestion_id', sa.UUID(), nullable=True),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('was_promoted_to_creative_version', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_suggestion_id'], ['optimization_suggestions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_creative_version_id'], ['creative_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_generated_variants_parent_version', 'generated_variants', ['parent_creative_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generated_variants_parent_version', table_name='generated_variants')
    op.drop_table('generated_variants')
    op.drop_index('ix_prediction_visualizations_type', table_name='prediction_visualizations')
    op.drop_table('prediction_visualizations')
    op.drop_index('ix_prediction_timeline_points_result_time', table_name='prediction_timeline_points')
    op.drop_table('prediction_timeline_points')
    op.drop_index('ix_prediction_scores_type_value', table_name='prediction_scores')
    op.drop_table('prediction_scores')
    op.drop_index('ix_optimization_suggestions_result_status', table_name='optimization_suggestions')
    op.drop_table('optimization_suggestions')
    op.drop_index('ix_calibration_observations_score_type', table_name='calibration_observations')
    op.drop_index('ix_calibration_observations_metric_type', table_name='calibration_observations')
    op.drop_table('calibration_observations')
    op.drop_index('ix_upload_sessions_user_status_created_desc', table_name='upload_sessions')
    op.drop_index('ix_upload_sessions_user_status', table_name='upload_sessions')
    op.drop_index('ix_upload_sessions_project_status', table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_index('ix_prediction_results_version_created_at', table_name='prediction_results')
    op.drop_index('ix_prediction_results_project_created_at', table_name='prediction_results')
    op.drop_table('prediction_results')
    op.drop_index('ix_llm_evaluations_user_created_at', table_name='llm_evaluations')
    op.drop_index('ix_llm_evaluations_job_status', table_name='llm_evaluations')
    op.drop_table('llm_evaluations')
    op.drop_index('ix_job_metrics_job_name', table_name='job_metrics')
    op.drop_table('job_metrics')
    op.drop_table('creative_comparison_item_results')
    op.drop_index('ix_analysis_results_job_created_at', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('ix_stored_artifacts_user_status', table_name='stored_artifacts')
    op.drop_index('ix_stored_artifacts_storage_key', table_name='stored_artifacts')
    op.drop_index('ix_stored_artifacts_project_user_kind_status_media_created_desc', table_name='stored_artifacts')
    op.drop_index('ix_stored_artifacts_project_user_kind_status_created_desc', table_name='stored_artifacts')
    op.drop_index('ix_stored_artifacts_project_kind', table_name='stored_artifacts')
    op.drop_table('stored_artifacts')
    op.drop_index('ix_outcome_events_project_metric', table_name='outcome_events')
    op.drop_index('ix_outcome_events_observed_at', table_name='outcome_events')
    op.drop_index('ix_outcome_events_creative_metric', table_name='outcome_events')
    op.drop_table('outcome_events')
    op.drop_index('ix_inference_jobs_status_created_at_desc', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_project_user_surface_media_created_desc', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_project_user_surface_media_created', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_project_user_created_at', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_project_status_surface_media_created_desc', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_project_status', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_project_goal_template', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_project_channel', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_execution_phase_updated_at', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_execution_phase', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_creative_status', table_name='inference_jobs')
    op.drop_index('ix_inference_jobs_created_at', table_name='inference_jobs')
    op.drop_table('inference_jobs')
    op.drop_table('creative_comparison_results')
    op.drop_index('ix_creative_comparison_items_rank', table_name='creative_comparison_items')
    op.drop_table('creative_comparison_items')
    op.drop_index('ix_asset_embeddings_version_kind', table_name='asset_embeddings')
    op.drop_table('asset_embeddings')
    op.drop_index('ix_creative_versions_creative_latest', table_name='creative_versions')
    op.drop_table('creative_versions')
    op.drop_index('ix_collaboration_comments_review_created_at', table_name='collaboration_comments')
    op.drop_table('collaboration_comments')
    op.drop_index('ix_creatives_project_status', table_name='creatives')
    op.drop_index('ix_creatives_project_name', table_name='creatives')
    op.drop_table('creatives')
    op.drop_index('ix_creative_comparisons_project_name', table_name='creative_comparisons')
    op.drop_table('creative_comparisons')
    op.drop_index('ix_collaboration_reviews_project_status', table_name='collaboration_reviews')
    op.drop_index('ix_collaboration_reviews_project_assignee', table_name='collaboration_reviews')
    op.drop_table('collaboration_reviews')
    op.drop_index('ix_campaigns_project_name', table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_workspace_invites_org_status', table_name='workspace_invites')
    op.drop_index('ix_workspace_invites_email_status', table_name='workspace_invites')
    op.drop_table('workspace_invites')
    op.drop_index('ix_webhook_endpoints_org_active', table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index('ix_user_sessions_user_revoked', table_name='user_sessions')
    op.drop_index('ix_user_sessions_org_user', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_mfa_credentials_user_enabled', table_name='user_mfa_credentials')
    op.drop_table('user_mfa_credentials')
    op.drop_index('ix_settings_org_group', table_name='settings')
    op.drop_table('settings')
    op.drop_index('ix_projects_org_name', table_name='projects')
    op.drop_index('ix_projects_org_created_at', table_name='projects')
    op.drop_table('projects')
    op.drop_table('organization_sso_configs')
    op.drop_table('organization_memberships')
    op.drop_index('ix_audit_logs_org_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_api_keys_org_status', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_index('ix_model_registry_kind_active', table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
