from __future__ import annotations

import json
from abc import ABC
from typing import Any

from backend.schemas.evaluators import EvaluationMode, evaluation_json_schema

BASE_SYSTEM_PROMPT = """You are a specialist evaluation engine embedded inside a media-analysis product.

Core operating principles:
1. The structured analysis payload is the source of truth for metrics, timings, and segment evidence.
2. Do not invent facts about raw media content, visuals, transcript wording, or performance signals that are not present in the provided context.
3. If you make an inference, it must remain conservative and traceable to the supplied evidence.
4. Use calibrated, product-friendly language. Avoid hype, filler, and vague praise.
5. Recommendations must be concise, operational, and prioritized by impact.
6. Tie claims to timestamps, segment labels, metric patterns, or explicit notes whenever available.
7. Timestamps must stay in milliseconds and must align with the provided analysis context.
8. Higher risk score means greater concern and worse risk posture.
9. When evidence is incomplete, state the limitation instead of guessing.
10. Return JSON only, matching the required schema exactly.
"""

BASE_DEVELOPER_PROMPT = """Use only the supplied structured context:
- job metadata
- summary metrics
- condensed metric table
- timeline highlights and patterns
- best and worst segments
- deterministic recommendations already generated by the analysis pipeline
- transcript excerpt or text excerpt if present
- keyframe descriptors if present

Output constraints:
- All scores must be grounded in the provided evidence.
- Strengths and weaknesses should be short, distinct, and non-redundant.
- Risks should be concrete and severity-calibrated.
- Recommendations should explain both the action and the reason.
- Populate the domain-specific fields relevant to the active mode.
- Leave irrelevant domain-specific fields empty or null.
- Return strict JSON only. No markdown. No commentary outside the JSON object.
"""


class BaseEvaluator(ABC):
    mode: EvaluationMode
    prompt_version: str = "v2"
    identity: str
    mission: str
    critical_rules: tuple[str, ...]
    evaluation_workflow: tuple[str, ...]
    domain_rubric: tuple[str, ...]
    output_requirements: tuple[str, ...]
    success_criteria: tuple[str, ...]

    def get_response_schema(self) -> dict[str, Any]:
        return evaluation_json_schema()

    def normalize_context(self, context: dict[str, Any]) -> dict[str, Any]:
        return context

    def build_domain_prompt(self) -> str:
        sections = [
            f"Identity:\n{self.identity}",
            f"Mission:\n{self.mission}",
            "Critical rules:\n" + "\n".join(f"{index + 1}. {item}" for index, item in enumerate(self.critical_rules)),
            "Evaluation workflow:\n"
            + "\n".join(f"{index + 1}. {item}" for index, item in enumerate(self.evaluation_workflow)),
            "Domain rubric:\n" + "\n".join(f"- {item}" for item in self.domain_rubric),
            "Output contract:\n" + "\n".join(f"- {item}" for item in self.output_requirements),
            "Success criteria:\n" + "\n".join(f"- {item}" for item in self.success_criteria),
        ]
        return "\n\n".join(sections)

    def build_messages(self, context: dict[str, Any]) -> list[dict[str, str]]:
        normalized = self.normalize_context(context)
        schema_json = json.dumps(self.get_response_schema(), ensure_ascii=True, separators=(",", ":"))
        context_json = json.dumps(normalized, ensure_ascii=True, separators=(",", ":"))
        user_prompt = (
            f"Active evaluation mode: {self.mode.value}\n"
            f"Prompt version: {self.prompt_version}\n"
            "Required JSON schema:\n"
            f"{schema_json}\n\n"
            "Structured analysis context:\n"
            f"{context_json}"
        )

        return [
            {"role": "system", "content": BASE_SYSTEM_PROMPT},
            {"role": "system", "content": self.build_domain_prompt()},
            {"role": "system", "content": BASE_DEVELOPER_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

    def build_prompt(self, context: dict[str, Any]) -> dict[str, Any]:
        return {
            "mode": self.mode.value,
            "prompt_version": self.prompt_version,
            "response_schema": self.get_response_schema(),
            "messages": self.build_messages(context),
        }
